Create patch set 2
Uploaded patch set 2: New patch set was added with same tree, parent, and commit message as Patch Set 1.

Patch-set: 2
Subject: Fix NoSuchMethodError for getTypeInfo()
Commit: 10b21f2406381a9688ddfbf71c6450f2b05d4b81
Tag: autogenerated:gerrit:newPatchSet
Groups: 2716c26c23ba7f8a6e2ffa194cd01edabb65abb3