Create patch set 3
Uploaded patch set 3: New patch set was added with same tree, parent, and commit message as Patch Set 2.

Patch-set: 3
Subject: Fix NoSuchMethodError for getTypeInfo()
Commit: cec9af53fc16bb7f5df639e2b5ab822136c0f552
Tag: autogenerated:gerrit:newPatchSet
Groups: 168e0e0eda7ebb9fca1a9436ded5e16aef73af41